### ISSUE TITLE
type definition error

### ISSUE THREAD

**Issue by ianhe8x** [cennznet/api.js#27]
when upgrade to 0.14.0, projects depends on `@cennznet/api` will get an error complaining a non compatible signature.
```
../node_modules/@cennznet/api/Api.d.ts:10:14 - error TS2416: Property 'tx' in type 'Api' is not assignable to the same property in base type 'ApiPromise'.
,,,
10     readonly tx: SubmittableExtrinsics<CodecResult, SubscriptionResult>;
```

which is because the suppression(`//@ts-ignore`) we use in the source code isn't brought to d.ts.
